# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercato_lotteries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='winnerdrawing',
            name='is_shipped',
            field=models.BooleanField(default=False, help_text='Se il premio è stato spedito al vincitore'),
        ),
        migrations.AddField(
            model_name='winnerdrawing',
            name='shipped_at',
            field=models.DateTimeField(blank=True, help_text='Data e ora di spedizione del premio', null=True),
        ),
    ]
