# Generated by Django 6.0.3 on 2026-03-24 18:48

import django.db.models.deletion
import mercato_lotteries.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercato_lotteries', '0006_add_auction_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='regione',
            options={'ordering': ['name']},
        ),
        migrations.RenameIndex(
            model_name='auction',
            new_name='mercato_lot_status_8d548c_idx',
            old_name='mercato_auc_status_idx',
        ),
        migrations.RenameIndex(
            model_name='auction',
            new_name='mercato_lot_seller__40fbc2_idx',
            old_name='mercato_auc_seller_idx',
        ),
        migrations.RenameIndex(
            model_name='auction',
            new_name='mercato_lot_auction_3df5e7_idx',
            old_name='mercato_auc_end_time_idx',
        ),
        migrations.RenameIndex(
            model_name='auction',
            new_name='mercato_lot_current_f7eef8_idx',
            old_name='mercato_auc_highest_idx',
        ),
        migrations.RenameIndex(
            model_name='auctionresult',
            new_name='mercato_lot_status_d92444_idx',
            old_name='mercato_ares_status_idx',
        ),
        migrations.RenameIndex(
            model_name='bid',
            new_name='mercato_lot_auction_a2600c_idx',
            old_name='mercato_bid_auc_idx',
        ),
        migrations.RenameIndex(
            model_name='bid',
            new_name='mercato_lot_bidder__2a622b_idx',
            old_name='mercato_bid_bidder_idx',
        ),
        migrations.RenameIndex(
            model_name='bid',
            new_name='mercato_lot_amount_b47c62_idx',
            old_name='mercato_bid_amount_idx',
        ),
        migrations.AlterField(
            model_name='auction',
            name='current_highest_bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winning_auctions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auction',
            name='image_1',
            field=mercato_lotteries.models.CompressedImageField(),
        ),
        migrations.AlterField(
            model_name='auction',
            name='image_2',
            field=mercato_lotteries.models.CompressedImageField(),
        ),
        migrations.AlterField(
            model_name='auction',
            name='image_3',
            field=mercato_lotteries.models.CompressedImageField(),
        ),
        migrations.AlterField(
            model_name='auction',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions_as_seller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auctionresult',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_auctions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_bids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together={('auction', 'bidder', 'created_at')},
        ),
        migrations.AlterModelTable(
            name='auction',
            table=None,
        ),
        migrations.AlterModelTable(
            name='auctionresult',
            table=None,
        ),
        migrations.AlterModelTable(
            name='bid',
            table=None,
        ),
    ]
