# Generated by Django 6.0.3 on 2026-03-24 18:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('kyc_approve', 'Approvazione KYC'), ('kyc_reject', 'Rifiuto KYC'), ('lottery_approve', 'Approvazione Lotteria'), ('lottery_reject', 'Rifiuto Lotteria'), ('payment_refund', 'Rimborso Pagamento'), ('banner_create', 'Creazione Banner'), ('banner_update', 'Aggiornamento Banner'), ('banner_delete', 'Eliminazione Banner'), ('csv_export', 'Esportazione CSV'), ('system_setting', 'Modifica Impostazioni'), ('other', 'Altro')], max_length=50)),
                ('action_description', models.TextField()),
                ('related_model', models.CharField(blank=True, max_length=100)),
                ('related_id', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Action Log',
                'verbose_name_plural': 'Admin Action Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KYCDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('id_card', "Carta d'Identità"), ('passport', 'Passaporto'), ('driver_license', 'Patente di Guida'), ('utility_bill', 'Bolla Utente'), ('other', 'Altro')], max_length=50)),
                ('document_file', models.FileField(upload_to='kyc_documents/')),
                ('status', models.CharField(choices=[('pending', 'In Attesa'), ('approved', 'Approvato'), ('rejected', 'Rifiutato')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_kyc_documents', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KYC Document',
                'verbose_name_plural': 'KYC Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('banner_type', models.CharField(choices=[('info', 'Informazione'), ('success', 'Successo'), ('warning', 'Avviso'), ('error', 'Errore'), ('promotion', 'Promozione')], default='info', max_length=20)),
                ('position', models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('modal', 'Modal')], default='top', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('link_url', models.URLField(blank=True)),
                ('link_text', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_banners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site Banner',
                'verbose_name_plural': 'Site Banners',
                'ordering': ['-created_at'],
            },
        ),
    ]
