# Generated by Django 6.0.3 on 2026-03-24 18:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#007bff', max_length=7)),
                ('icon', models.CharField(default='bell', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('info', 'Informazione'), ('success', 'Successo'), ('warning', 'Avviso'), ('error', 'Errore'), ('lottery', 'Lotteria'), ('payment', 'Pagamento'), ('system', 'Sistema')], default='info', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('low', 'Bassa'), ('normal', 'Normale'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=10)),
                ('action_url', models.URLField(blank=True)),
                ('action_text', models.CharField(blank=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='mercato_notifications.notificationcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'In Attesa'), ('sent', 'Inviato'), ('delivered', 'Consegnato'), ('failed', 'Fallito'), ('bounced', 'Rimbalzato')], default='pending', max_length=20)),
                ('external_message_id', models.CharField(blank=True, max_length=100, null=True)),
                ('provider', models.CharField(default='smtp', max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_notification', to='mercato_notifications.notification')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True)),
                ('email_lottery_results', models.BooleanField(default=True)),
                ('email_new_lotteries', models.BooleanField(default=True)),
                ('email_payment_updates', models.BooleanField(default=True)),
                ('email_system_updates', models.BooleanField(default=False)),
                ('push_enabled', models.BooleanField(default=True)),
                ('push_lottery_results', models.BooleanField(default=True)),
                ('push_new_lotteries', models.BooleanField(default=True)),
                ('push_payment_updates', models.BooleanField(default=True)),
                ('push_system_updates', models.BooleanField(default=False)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('sms_phone_number', models.CharField(blank=True, max_length=17)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Settings',
                'verbose_name_plural': 'Notification Settings',
            },
        ),
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_token', models.CharField(max_length=255)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'In Attesa'), ('sent', 'Inviato'), ('delivered', 'Consegnato'), ('failed', 'Fallito')], default='pending', max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='push_notification', to='mercato_notifications.notification')),
            ],
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('from_email', models.EmailField(default='', max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('template_used', models.CharField(choices=[('registration', 'Registrazione'), ('kyc_approved', 'KYC Approvato'), ('kyc_rejected', 'KYC Rifiutato'), ('lottery_activated', 'Lotteria Attivata'), ('ticket_purchased', 'Biglietto Acquistato'), ('lottery_won', 'Vincita Lotteria'), ('seller_winner_notification', 'Notifica Venditore Vincitore'), ('lottery_lost', 'Perdita Lotteria'), ('expiration_reminder', 'Promemoria Scadenza'), ('custom', 'Personalizzato')], default='custom', max_length=50)),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'In Attesa'), ('sent', 'Inviato'), ('delivered', 'Consegnato'), ('failed', 'Fallito'), ('bounced', 'Rimbalzato'), ('retry', 'In Retry')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Bassa'), ('normal', 'Normale'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=10)),
                ('provider', models.CharField(default='smtp', max_length=50)),
                ('external_message_id', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='mercato_not_status_c98c26_idx'), models.Index(fields=['user', 'status'], name='mercato_not_user_id_b21d70_idx'), models.Index(fields=['template_used', 'status'], name='mercato_not_templat_b20e42_idx'), models.Index(fields=['recipient_email', 'status'], name='mercato_not_recipie_d0e6e6_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='mercato_not_user_id_adbdbc_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['category', 'is_read'], name='mercato_not_categor_38fe5e_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['scheduled_for'], name='mercato_not_schedul_f0b285_idx'),
        ),
    ]
